export const organisation = {
    ORGANISATION_GET_LIST: 'ORGANISATION_GET_LIST',
    SAGA_ORGANISATION_GET_LIST: 'SAGA_ORGANISATION_GET_LIST',
    ADD_ORGANISATION: 'ADD_ORGANISATION',
    SAGA_ADD_ORGANISATION: 'SAGA_ADD_ORGANISATION',
}
